# Configuration du site

# Importer le thème
theme: jekyll-theme-chirpy

# Langue du site › http://www.lingoes.net/en/translator/langcode.htm
# Si elle correspond à un fichier dans le dossier `_data/locales`, la langue de l'interface sera changée,
# sinon, la langue par défaut sera l'anglais ('en').
lang: fr

# Définir votre fuseau horaire › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Africa/Ouagadougou

# Paramètres de jekyll-seo-tag › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Black As Day # titre principal

tagline: Pour ceux qui veulent comprendre, construire et transmettre. # sous-titre affiché

description: >-
  Ce blog existe pour informer la jeunesse africaine et éclairer les générations futures. Nous explorons le passé, le présent et l’avenir pour nourrir la vérité et laisser une trace.

# Renseignez le protocole et le nom d'hôte de votre site.
# Exemple : 'https://utilisateur.github.io' — ne pas inclure de '/' à la fin.
url: "https://ebrice241.github.io/Black-As-Day/"

github:
  username: github_username # remplacez par votre nom d'utilisateur GitHub

twitter:
  username: twitter_username # remplacez par votre nom d'utilisateur Twitter

social:
  # Remplacez par votre nom complet.
  # Il s'affichera comme auteur par défaut des articles et comme détenteur des droits d'auteur dans le pied de page
  name: Ebrice241
  email: contact@example.com # remplacez par votre adresse email
  links:
    - https://twitter.com/Ebrice241_CLONE
    - https://github.com/github_username

# Paramètres de vérification du site
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# ↑ --------------------------
# Fin des paramètres jekyll-seo-tag

# Paramètres d'analyse Web
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# Paramètres de vues des pages
pageviews:
  provider:

# Préférence de thème (clair/sombre).
# Laisser vide suit la préférence système avec un bouton pour changer le thème.
# Options disponibles : light | dark
theme_mode:

# CDN pour les ressources médias.
cdn: "https://chirpy-img.netlify.app"

# Avatar dans la barre latérale, supporte les ressources locales ou CORS
avatar: "/commons/avatar.jpg"

# Image de prévisualisation utilisée dans les métadonnées SEO `og:image`
social_preview_image:

# Activer ou non la table des matières (TOC) dans les articles.
toc: true

comments:
  provider:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

# Hébergement de ressources statiques auto-hébergées › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true # activer la fonctionnalité PWA (installable)
  cache:
    enabled: true # activer le cache hors-ligne PWA
    deny_paths:

paginate: 10

# Base URL du site
baseurl: ""

# ------------ Options suivantes déconseillées à modifier ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

